-- Tabela para processamentos de cartão de crédito off-line
CREATE TABLE IF NOT EXISTS offline_credit_card_processings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  processing_number VARCHAR(50) NOT NULL COMMENT 'Número do processamento',
  client_id BIGINT UNSIGNED NOT NULL COMMENT 'ID do cliente',
  invoice_id BIGINT UNSIGNED NULL COMMENT 'ID da fatura (se aplicável)',
  order_id BIGINT UNSIGNED NULL COMMENT 'ID do pedido (se aplicável)',
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'Valor do processamento',
  currency VARCHAR(10) NOT NULL DEFAULT 'BRL' COMMENT 'Moeda',
  card_type VARCHAR(20) NULL COMMENT 'Tipo de cartão: visa, mastercard, amex, elo, diners, other',
  card_last_four VARCHAR(4) NULL COMMENT 'Últimos 4 dígitos do cartão',
  card_holder_name VARCHAR(255) NULL COMMENT 'Nome do portador do cartão',
  installments INT NOT NULL DEFAULT 1 COMMENT 'Número de parcelas',
  processing_method VARCHAR(50) NOT NULL DEFAULT 'manual' COMMENT 'Método: manual, terminal, phone, email',
  authorization_code VARCHAR(50) NULL COMMENT 'Código de autorização',
  transaction_id VARCHAR(255) NULL COMMENT 'ID da transação',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'Status: pending, authorized, captured, declined, cancelled, refunded',
  authorization_date DATETIME NULL COMMENT 'Data/hora da autorização',
  capture_date DATETIME NULL COMMENT 'Data/hora da captura',
  cvv_verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'CVV verificado',
  address_verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Endereço verificado',
  risk_score INT NULL COMMENT 'Score de risco (0-100)',
  processor_response TEXT NULL COMMENT 'Resposta do processador',
  notes TEXT NULL COMMENT 'Observações',
  processed_by BIGINT UNSIGNED NULL COMMENT 'ID do administrador que processou',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de criação',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_processing_number (processing_number),
  KEY idx_processing_client (client_id),
  KEY idx_processing_invoice (invoice_id),
  KEY idx_processing_order (order_id),
  KEY idx_processing_status (status),
  KEY idx_processing_method (processing_method),
  KEY idx_processing_created (created_at),
  CONSTRAINT fk_processing_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_processing_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_processing_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_processing_admin FOREIGN KEY (processed_by) REFERENCES admin_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

