-- Tabela para logs de transações do gateway
CREATE TABLE IF NOT EXISTS gateway_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  transaction_number VARCHAR(50) NOT NULL COMMENT 'Número da transação (interno)',
  gateway VARCHAR(50) NOT NULL COMMENT 'Gateway: stripe, paypal, pagseguro, mercadopago, other',
  gateway_transaction_id VARCHAR(255) NULL COMMENT 'ID da transação no gateway',
  transaction_type VARCHAR(50) NOT NULL DEFAULT 'payment' COMMENT 'Tipo: payment, refund, subscription, webhook, other',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'Status: success, failed, pending, cancelled, refunded',
  client_id BIGINT UNSIGNED NULL COMMENT 'ID do cliente (se aplicável)',
  invoice_id BIGINT UNSIGNED NULL COMMENT 'ID da fatura (se aplicável)',
  order_id BIGINT UNSIGNED NULL COMMENT 'ID do pedido (se aplicável)',
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'Valor da transação',
  currency VARCHAR(10) NOT NULL DEFAULT 'BRL' COMMENT 'Moeda',
  payment_method VARCHAR(50) NULL COMMENT 'Método de pagamento: credit_card, debit_card, pix, boleto, bank_transfer',
  card_type VARCHAR(20) NULL COMMENT 'Tipo de cartão (se aplicável)',
  card_last_four VARCHAR(4) NULL COMMENT 'Últimos 4 dígitos do cartão',
  installments INT NULL COMMENT 'Número de parcelas',
  request_data JSON NULL COMMENT 'Dados da requisição enviada ao gateway',
  response_data JSON NULL COMMENT 'Dados da resposta do gateway',
  error_code VARCHAR(50) NULL COMMENT 'Código do erro (se houver)',
  error_message TEXT NULL COMMENT 'Mensagem de erro (se houver)',
  webhook_received TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Webhook recebido',
  webhook_data JSON NULL COMMENT 'Dados do webhook recebido',
  ip_address VARCHAR(45) NULL COMMENT 'Endereço IP da requisição',
  user_agent TEXT NULL COMMENT 'User agent da requisição',
  processing_time_ms INT NULL COMMENT 'Tempo de processamento em milissegundos',
  notes TEXT NULL COMMENT 'Observações adicionais',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de criação',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_transaction_number (transaction_number),
  KEY idx_gateway (gateway),
  KEY idx_gateway_transaction_id (gateway_transaction_id),
  KEY idx_transaction_type (transaction_type),
  KEY idx_status (status),
  KEY idx_client (client_id),
  KEY idx_invoice (invoice_id),
  KEY idx_order (order_id),
  KEY idx_created (created_at),
  KEY idx_status_created (status, created_at),
  CONSTRAINT fk_gateway_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_gateway_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_gateway_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

